project:
  type: website
  output-dir: docs

website:
  title: "Examening Education and Cancer Mortality"
  search: false
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd #person A
        text: Home
      - href: abstract.qmd #person B
        text: Abstract

format:
  html:
    theme: superhero
    css: style.css
    toc: true
    code-fold: true
