project:
  type: website
  output-dir: docs

website:
  title: "Examening Education and Cancer Mortality"
  search: false
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd #Sophie
        text: Home
      - href: abstract.qmd #Sophie
        text: Abstract
      - href: index.qmd #Sophie
        text: Background
      - href: index.qmd #Sophie
        text: Purpose of Research
      - href: index.qmd #Emily
        text: Methods
      - href: index.qmd #Emily
        text: Results and Findings
      - href: index.qmd #Sophie
        text: Conclusion

format:
  html:
    theme: superhero
    css: style.css
    toc: true
    code-fold: true
